"""
Django settings for cointex project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# --- Paths ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Segurança / Debug -----------------------------------------------
def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return str(val).lower() in ("1", "true", "yes", "y", "on")

# NUNCA deixe string "True" aqui; use env var
DEBUG = env_bool("DEBUG", False)

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-0kaay6yyas=1an#cb=+!y7l77kfeo=hsgrn1eop$u7fm7h^5c5"
)

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()
]

# Render injeta o hostname público
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# --- CSRF Trusted Origins (precisam ter esquema http/https) ----------
CSRF_TRUSTED_ORIGINS = []

def _add_origin(origin: str):
    o = origin.strip()
    if not o:
        return
    # localhost/127.0.0.1: adicione http e https
    if o in ("localhost", "127.0.0.1", "0.0.0.0") or o.startswith("localhost:") or o.startswith("127.0.0.1:"):
        CSRF_TRUSTED_ORIGINS.extend([f"http://{o}", f"https://{o}"])
    else:
        CSRF_TRUSTED_ORIGINS.append(o if o.startswith("http") else f"https://{o}")

# 1) De env explícito (recomendado em prod)
for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(","):
    _add_origin(o)

# 2) URL pública do Render (se existir)
render_external_url = os.getenv("RENDER_EXTERNAL_URL")
if render_external_url:
    _add_origin(render_external_url)

# 3) Derivar de ALLOWED_HOSTS
for host in ALLOWED_HOSTS:
    _add_origin(host)

# Remover duplicatas mantendo a ordem
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Cookies seguros em produção
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE   = env_bool("CSRF_COOKIE_SECURE", True)
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")

# Em proxies (Render), reconheça HTTPS corretamente
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Domínio de cookie: só defina via ENV para não quebrar local
COOKIE_DOMAIN = os.getenv("COOKIE_DOMAIN")  # ex: ".cointex.cash"
if COOKIE_DOMAIN:
    SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
    CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN

# --- Apps ------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "rest_framework",
    "core",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.CanonicalHostMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cointex.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cointex.wsgi.application"

# --- Banco de Dados ---------------------------------------------------
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "300")),
        conn_health_checks=True,
    )
}
DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}

# --- Validação de Senhas ----------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Cache / Sessão (Redis) -------------------------------------------
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": "cointex",
            # TIMEOUT padrão (segundos) — opcional
            # "TIMEOUT": int(os.getenv("DJANGO_CACHE_TIMEOUT", "300")),
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "cointex-cache",
        }
    }

# TTLs tunáveis por ENV
PIX_STATUS_TTL_SECONDS   = int(os.getenv("PIX_STATUS_TTL", "2"))
WALLET_CACHE_TTL_SECONDS = int(os.getenv("WALLET_CACHE_TTL", "60"))
LOG_SAMPLE_RATE          = float(os.getenv("LOG_SAMPLE_RATE", "0.05"))

# --- i18n / tz --------------------------------------------------------
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
# (USE_L10N foi removido no Django 5+)

# --- Static files / WhiteNoise ----------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Inclua 'static/' do projeto apenas se existir (evita warning em produção)
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []

# Django 5+ estilo STORAGES (preferível ao STATICFILES_STORAGE)
if not DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# --- Defaults / Auth --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.CustomUser"

LOGIN_REDIRECT_URL = "home"
LOGIN_URL = "/accounts/entrar/"

DATE_FORMAT = "d/m/Y"
DATE_INPUT_FORMATS = ["%d/%m/%Y", "%Y-%m-%d"]

AUTHENTICATION_BACKENDS = ["accounts.backends.EmailBackend"]

# --- Outros -----------------------------------------------------------
CAPI_TOKEN = os.getenv("CAPI_TOKEN")
