# Generated by Django 5.2.4 on 2025-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('galaxify', 'Galaxify'), ('tribopay', 'TriboPay')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gateway de Pagamento',
                'verbose_name_plural': 'Gateways de Pagamento',
            },
        ),
    ]
