# Generated by Django 5.2.4 on 2025-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(choices=[('galaxify', 'Galaxify'), ('tribopay', 'TriboPay'), ('veltrax', 'Veltrax')], max_length=20, unique=True),
        ),
    ]
