# Generated by Django 5.2.4 on 2025-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtwaAdCatalog',
            fields=[
                ('ad_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adset_id', models.CharField(blank=True, max_length=32, null=True)),
                ('adset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=32, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ctwa_ad_catalog',
            },
        ),
    ]
