# Generated by Django 5.2.4 on 2025-08-11 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone para verificação ou notificações.', max_length=15, null=True, verbose_name='Número de telefone')),
                ('date_of_birth', models.DateField(blank=True, help_text='Necessário para verificação de idade e KYC. Deve ser maior de 18 anos.', null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(blank=True, help_text='CPF no formato 000.000.000-00. Obrigatório para usuários brasileiros.', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica se o usuário passou por verificação KYC, incluindo validação de CPF.', verbose_name='Usuário verificado')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Habilita 2FA para maior segurança.', verbose_name='Autenticação de dois fatores ativada')),
                ('referral_code', models.CharField(blank=True, help_text='Código único para programa de referências.', max_length=10, null=True, unique=True, verbose_name='Código de indicação')),
                ('username', models.CharField(blank=True, error_messages={'unique': 'Um usuário com esse nome já existe.'}, help_text='Opcional. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('uid_code', models.CharField(blank=True, editable=False, help_text='Código alfanumérico único de 12 caracteres para exibição pública.', max_length=12, null=True, unique=True, verbose_name='Código UID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_advanced_verified', models.BooleanField(default=False, help_text='Indica se o usuário passou por verificação avançada com selfie.', verbose_name='Verificação Avançada')),
                ('withdrawal_pin', models.CharField(default='8293', editable=False, help_text='PIN fixo de 4 dígitos para saques (8293 para todas as contas).', max_length=4, verbose_name='PIN de Saque')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='PixTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=12, unique=True, verbose_name='External ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='Status')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code Payload')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Imagem QR Code')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação PIX',
                'verbose_name_plural': 'Transações PIX',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Ex: 'Login Diário', 'Referência'", max_length=50, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=10, verbose_name='Moeda')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Resgatada')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, help_text='Endereço para verificação KYC.', null=True, verbose_name='Endereço físico')),
                ('preferred_currency', models.CharField(default='BRL', help_text='Ex: BRL, USD, EUR para exibição de saldos.', max_length=3, verbose_name='Moeda fiat preferida')),
                ('wallet_address_btc', models.CharField(blank=True, help_text='Endereço público para Bitcoin. Nunca armazene chaves privadas!', max_length=100, null=True, verbose_name='Endereço BTC')),
                ('wallet_address_eth', models.CharField(blank=True, help_text='Endereço público para Ethereum/ERC-20.', max_length=100, null=True, verbose_name='Endereço ETH')),
                ('country', models.CharField(default='Brasil', help_text='País de residência para KYC.', max_length=100, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano')], default='BRL', max_length=10, verbose_name='Moeda Principal')),
                ('address', models.CharField(blank=True, help_text='Endereço da wallet; nunca armazene chaves privadas!', max_length=100, null=True, verbose_name='Endereço Público')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, help_text='Saldo atual na moeda principal', max_digits=18, verbose_name='Saldo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAW', 'Saque'), ('SEND', 'Envio'), ('RECEIVE', 'Recebimento'), ('CONVERT', 'Conversão')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Quantidade')),
                ('currency', models.CharField(max_length=10, verbose_name='Moeda')),
                ('to_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço Destino')),
                ('from_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço Origem')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Completa'), ('FAILED', 'Falha')], default='PENDING', max_length=20, verbose_name='Status')),
                ('transaction_hash', models.CharField(blank=True, help_text='Para blockchain', max_length=100, null=True, verbose_name='Hash da Transação')),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Taxa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BRL', 'Real'), ('USD', 'Dólar')], max_length=10, verbose_name='Moeda')),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Quantidade')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
                'unique_together': {('wallet', 'currency')},
            },
        ),
    ]
