# Generated by Django 5.2.4 on 2025-08-05 23:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone para verificação ou notificações.', max_length=15, null=True, verbose_name='Número de telefone')),
                ('date_of_birth', models.DateField(blank=True, help_text='Necessário para verificação de idade e KYC. Deve ser maior de 18 anos.', null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(blank=True, help_text='CPF no formato 000.000.000-00. Obrigatório para usuários brasileiros.', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica se o usuário passou por verificação KYC, incluindo validação de CPF.', verbose_name='Usuário verificado')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Habilita 2FA para maior segurança.', verbose_name='Autenticação de dois fatores ativada')),
                ('referral_code', models.CharField(blank=True, help_text='Código único para programa de referências.', max_length=10, null=True, unique=True, verbose_name='Código de indicação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, help_text='Endereço para verificação KYC.', null=True, verbose_name='Endereço físico')),
                ('preferred_currency', models.CharField(default='BRL', help_text='Ex: BRL, USD, EUR para exibição de saldos.', max_length=3, verbose_name='Moeda fiat preferida')),
                ('wallet_address_btc', models.CharField(blank=True, help_text='Endereço público para Bitcoin. Nunca armazene chaves privadas!', max_length=100, null=True, verbose_name='Endereço BTC')),
                ('wallet_address_eth', models.CharField(blank=True, help_text='Endereço público para Ethereum/ERC-20.', max_length=100, null=True, verbose_name='Endereço ETH')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
