# Generated by Django 5.2.4 on 2025-08-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Tracking ID'),
        ),
    ]
