# Generated by Django 5.2.4 on 2025-08-07 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Ex: 'Login Diário', 'Referência'", max_length=50, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=10, verbose_name='Moeda')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Resgatada')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano')], default='BRL', max_length=10, verbose_name='Moeda Principal')),
                ('address', models.CharField(blank=True, help_text='Endereço da wallet; nunca armazene chaves privadas!', max_length=100, null=True, verbose_name='Endereço Público')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, help_text='Saldo atual na moeda principal', max_digits=18, verbose_name='Saldo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAW', 'Saque'), ('SEND', 'Envio'), ('RECEIVE', 'Recebimento'), ('CONVERT', 'Conversão')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Quantidade')),
                ('currency', models.CharField(max_length=10, verbose_name='Moeda')),
                ('to_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço Destino')),
                ('from_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço Origem')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Completa'), ('FAILED', 'Falha')], default='PENDING', max_length=20, verbose_name='Status')),
                ('transaction_hash', models.CharField(blank=True, help_text='Para blockchain', max_length=100, null=True, verbose_name='Hash da Transação')),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Taxa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BRL', 'Real'), ('USD', 'Dólar')], max_length=10, verbose_name='Moeda')),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Quantidade')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
                'unique_together': {('wallet', 'currency')},
            },
        ),
    ]
