# Generated by Django 5.2.4 on 2025-08-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Tracking ID'),
        ),
    ]
