# Generated by Django 5.2.4 on 2025-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_reward_wallet_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_advanced_verified',
            field=models.BooleanField(default=False, help_text='Indica se o usuário passou por verificação avançada com selfie.', verbose_name='Verificação Avançada'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Brasil', help_text='País de residência para KYC.', max_length=100, verbose_name='País'),
        ),
    ]
