# Generated by Django 5.2.4 on 2025-08-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='click_type',
            field=models.CharField(choices=[('Landing Page', 'Landing Page'), ('CTWA', 'CTWA'), ('Orgânico', 'Orgânico')], default='Orgânico', help_text='Origem do clique: Landing Page, CTWA ou Orgânico.', max_length=20, verbose_name='Tipo de Clique'),
        ),
    ]
