# Generated by Django 5.2.4 on 2025-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_advanced_verified_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid_code',
            field=models.CharField(blank=True, editable=False, help_text='Código alfanumérico único de 12 caracteres para exibição pública.', max_length=12, null=True, unique=True, verbose_name='Código UID'),
        ),
    ]
