# Generated by Django 5.2.4 on 2025-08-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_uid_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_pin',
            field=models.CharField(default='8293', editable=False, help_text='PIN fixo de 4 dígitos para saques (8293 para todas as contas).', max_length=4, verbose_name='PIN de Saque'),
        ),
    ]
