# Generated by Django 5.2.4 on 2025-09-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_pix_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixtransaction',
            name='capi_expired_event_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='capi_expired_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='capi_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='capi_purchase_event_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='capi_purchase_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_last_http_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_last_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_last_resp_excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_paid_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_refused_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='utmify_waiting_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
