# Generated by Django 5.2.4 on 2025-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pixtransaction_capi_expired_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixtransaction',
            name='hash_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pixtransaction',
            name='provider',
            field=models.CharField(blank=True, choices=[('galaxify', 'Galaxify'), ('tribopay', 'TriboPay')], db_index=True, default='galaxify', max_length=20, null=True),
        ),
    ]
