# Generated by Django 5.2.4 on 2025-10-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pixtransaction_hash_id_pixtransaction_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
