# Generated by Django 5.2.4 on 2025-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_first_login_webhook_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixtransaction',
            name='provider',
            field=models.CharField(blank=True, choices=[('galaxify', 'Galaxify'), ('tribopay', 'TriboPay'), ('veltrax', 'Veltrax')], db_index=True, default='galaxify', max_length=20, null=True),
        ),
    ]
