# Generated by Django 5.2.4 on 2025-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20251114_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixtransaction',
            name='external_id',
            field=models.CharField(default='', max_length=128, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='pixtransaction',
            name='hash_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pixtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
