# Generated by Django 5.2.4 on 2025-09-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('provider', models.CharField(choices=[('meta', 'Meta Pixel'), ('ga4', 'Google Analytics 4'), ('tiktok', 'TikTok Pixel'), ('utmify', 'Utmify Pixel'), ('custom', 'Custom Script')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('include_paths', models.TextField(blank=True, default='')),
                ('exclude_paths', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de injeção (menor primeiro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServerPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('provider', models.CharField(choices=[('meta_capi', 'Meta CAPI')], default='meta_capi', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('pixel_id', models.CharField(blank=True, default='', help_text='Meta Pixel ID', max_length=64)),
                ('access_token', models.CharField(blank=True, default='', help_text='Meta CAPI Access Token', max_length=256)),
                ('test_event_code', models.CharField(blank=True, default='', help_text='Opcional (modo teste)', max_length=64)),
                ('send_purchase', models.BooleanField(default=True)),
                ('send_payment_expired', models.BooleanField(default=True)),
                ('send_initiate_checkout', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
