# Generated by Django 5.2.4 on 2025-09-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_enabled', models.BooleanField(default=True)),
                ('meta_pixel_ids', models.TextField(blank=True, default='', help_text='Um Pixel ID por linha (ex.: 111..., 222...).')),
                ('tiktok_enabled', models.BooleanField(default=False)),
                ('tiktok_pixel_id', models.CharField(blank=True, default='', max_length=64)),
                ('ga4_enabled', models.BooleanField(default=False)),
                ('ga4_measurement_id', models.CharField(blank=True, default='', max_length=40)),
                ('utmify_enabled', models.BooleanField(default=False)),
                ('utmify_pixel_id', models.CharField(blank=True, default='', max_length=64)),
                ('helper_enabled', models.BooleanField(default=True, help_text='Expor window.track no fim do <body>.')),
                ('custom_head_js', models.TextField(blank=True, default='', help_text='JS opcional a ser inserido no <head>.')),
                ('custom_body_js', models.TextField(blank=True, default='', help_text='JS opcional antes do </body>.')),
                ('exclude_admin', models.BooleanField(default=True, help_text='Não injetar pixels em /admin.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientPixel',
        ),
        migrations.AlterModelOptions(
            name='serverpixel',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='serverpixel',
            name='order',
        ),
    ]
