# Generated by Django 5.2.4 on 2025-09-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_clienttrackingconfig_delete_clientpixel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(help_text='Nome da rota (ex.: core:withdraw_validation)', max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fire_once_per_session', models.BooleanField(default=True, help_text='Disparar cada evento uma única vez por sessão')),
                ('fire_page_view', models.BooleanField(default=False)),
                ('page_view_params', models.TextField(blank=True, default='', help_text='JSON opcional')),
                ('fire_view_content', models.BooleanField(default=False)),
                ('view_content_params', models.TextField(blank=True, default='')),
                ('fire_search', models.BooleanField(default=False)),
                ('search_params', models.TextField(blank=True, default='')),
                ('fire_add_to_cart', models.BooleanField(default=False)),
                ('add_to_cart_params', models.TextField(blank=True, default='')),
                ('fire_add_to_wishlist', models.BooleanField(default=False)),
                ('add_to_wishlist_params', models.TextField(blank=True, default='')),
                ('fire_initiate_checkout', models.BooleanField(default=False)),
                ('initiate_checkout_params', models.TextField(blank=True, default='')),
                ('fire_add_payment_info', models.BooleanField(default=False)),
                ('add_payment_info_params', models.TextField(blank=True, default='')),
                ('fire_purchase', models.BooleanField(default=False)),
                ('purchase_params', models.TextField(blank=True, default='')),
                ('fire_lead', models.BooleanField(default=False)),
                ('lead_params', models.TextField(blank=True, default='')),
                ('fire_complete_registration', models.BooleanField(default=False)),
                ('complete_registration_params', models.TextField(blank=True, default='')),
                ('fire_subscribe', models.BooleanField(default=False)),
                ('subscribe_params', models.TextField(blank=True, default='')),
                ('fire_start_trial', models.BooleanField(default=False)),
                ('start_trial_params', models.TextField(blank=True, default='')),
                ('fire_contact', models.BooleanField(default=False)),
                ('contact_params', models.TextField(blank=True, default='')),
                ('fire_find_location', models.BooleanField(default=False)),
                ('find_location_params', models.TextField(blank=True, default='')),
                ('fire_schedule', models.BooleanField(default=False)),
                ('schedule_params', models.TextField(blank=True, default='')),
                ('fire_submit_application', models.BooleanField(default=False)),
                ('submit_application_params', models.TextField(blank=True, default='')),
                ('fire_customize_product', models.BooleanField(default=False)),
                ('customize_product_params', models.TextField(blank=True, default='')),
                ('fire_donate', models.BooleanField(default=False)),
                ('donate_params', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['view_name'],
            },
        ),
        migrations.AddField(
            model_name='clienttrackingconfig',
            name='ga4_auto_pageview',
            field=models.BooleanField(default=True, help_text='Enviar page_view automático (gtag config)'),
        ),
        migrations.AddField(
            model_name='clienttrackingconfig',
            name='meta_auto_pageview',
            field=models.BooleanField(default=True, help_text='Disparar PageView automático no Meta'),
        ),
        migrations.AddField(
            model_name='clienttrackingconfig',
            name='tiktok_auto_page',
            field=models.BooleanField(default=True, help_text='Chamar ttq.page() automático'),
        ),
        migrations.AddField(
            model_name='serverpixel',
            name='ga4_api_secret',
            field=models.CharField(blank=True, default='', help_text='GA4 API Secret', max_length=80),
        ),
        migrations.AddField(
            model_name='serverpixel',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, default='', help_text='GA4 Measurement ID (G-XXXX)', max_length=40),
        ),
        migrations.AddField(
            model_name='serverpixel',
            name='tiktok_access_token',
            field=models.CharField(blank=True, default='', help_text='TikTok Events API access token', max_length=256),
        ),
        migrations.AddField(
            model_name='serverpixel',
            name='tiktok_pixel_code',
            field=models.CharField(blank=True, default='', help_text='TikTok Pixel Code (ex.: CF... ou D31...)', max_length=80),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='custom_head_js',
            field=models.TextField(blank=True, default='', help_text='JS opcional no <head>.'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='meta_pixel_ids',
            field=models.TextField(blank=True, default='', help_text='Um Pixel ID por linha'),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='provider',
            field=models.CharField(choices=[('meta_capi', 'Meta CAPI'), ('ga4_mp', 'GA4 Measurement Protocol'), ('tiktok_eapi', 'TikTok Events API')], default='meta_capi', max_length=20),
        ),
    ]
