# Generated by Django 5.2.4 on 2025-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_sync_missing_pageevent_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='custom_body_js',
            field=models.TextField(blank=True, db_default='', default='', help_text='JS opcional antes do </body>.'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='custom_head_js',
            field=models.TextField(blank=True, db_default='', default='', help_text='JS opcional no <head>.'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='exclude_admin',
            field=models.BooleanField(db_default=True, default=True, help_text='Não injetar pixels em /admin.'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='ga4_auto_pageview',
            field=models.BooleanField(db_default=True, default=True, help_text='Enviar page_view automático (gtag config)'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='ga4_enabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='helper_enabled',
            field=models.BooleanField(db_default=True, default=True, help_text='Expor window.track no fim do <body>.'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='meta_auto_pageview',
            field=models.BooleanField(db_default=True, default=True, help_text='Disparar PageView automático no Meta'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='meta_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='meta_pixel_ids',
            field=models.TextField(blank=True, db_default='', default='', help_text='Um Pixel ID por linha'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='tiktok_auto_page',
            field=models.BooleanField(db_default=True, default=True, help_text='Chamar ttq.page() automático'),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='tiktok_enabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='utmify_enabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='clienttrackingconfig',
            name='utmify_pixel_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='add_payment_info_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='add_to_cart_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='add_to_wishlist_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='complete_registration_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='contact_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='customize_product_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='donate_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='find_location_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_add_payment_info',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_add_to_cart',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_add_to_wishlist',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_complete_registration',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_contact',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_customize_product',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_donate',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_find_location',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_initiate_checkout',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_lead',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_once_per_session',
            field=models.BooleanField(db_default=True, default=True, help_text='Disparar cada evento uma única vez por sessão'),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_page_view',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_purchase',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_schedule',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_search',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_start_trial',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_submit_application',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_subscribe',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='fire_view_content',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='initiate_checkout_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='lead_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='page_view_params',
            field=models.TextField(blank=True, db_default='', default='', help_text='JSON opcional'),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='purchase_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='schedule_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='search_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='start_trial_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='submit_application_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='subscribe_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='pageeventconfig',
            name='view_content_params',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='access_token',
            field=models.CharField(blank=True, db_default='', default='', help_text='Meta CAPI Access Token', max_length=256),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='ga4_api_secret',
            field=models.CharField(blank=True, db_default='', default='', help_text='GA4 API Secret', max_length=80),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, db_default='', default='', help_text='GA4 Measurement ID (G-XXXX)', max_length=40),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='pixel_id',
            field=models.CharField(blank=True, db_default='', default='', help_text='Meta Pixel ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='provider',
            field=models.CharField(choices=[('meta_capi', 'Meta CAPI'), ('ga4_mp', 'GA4 Measurement Protocol'), ('tiktok_eapi', 'TikTok Events API')], db_default='meta_capi', default='meta_capi', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='send_initiate_checkout',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='send_payment_expired',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='send_purchase',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='test_event_code',
            field=models.CharField(blank=True, db_default='', default='', help_text='Opcional (modo teste)', max_length=64),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='tiktok_access_token',
            field=models.CharField(blank=True, db_default='', default='', help_text='TikTok Events API access token', max_length=256),
        ),
        migrations.AlterField(
            model_name='serverpixel',
            name='tiktok_pixel_code',
            field=models.CharField(blank=True, db_default='', default='', help_text='TikTok Pixel Code (ex.: CF... ou D31...)', max_length=80),
        ),
    ]
