# Generated by Django 5.2.4 on 2025-09-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active_theme', models.CharField(choices=[('cointex', 'Cointex'), ('mpay', 'MPay')], default='cointex', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema do Site',
                'verbose_name_plural': 'Tema do Site',
            },
        ),
    ]
